### ISSUE TITLE
Supported Selenium version?

### ISSUE THREAD

**Issue by ghost** [OXID-eSales/testing_library#13]
Which version of Selenium should be supported by this test library? I use branch b-1.1 and in the Readme there is no information about specific requirements.

When I use a current Selenium (3.4.0) `docker run --rm -p 4444:4444 selenium/standalone-firefox:latest` runtests-selenium does not work:
> Selenium\Exception: Unexpected response from Selenium server

When I use an older Selenium (2.53.1) `docker run --rm -p 4444:4444 selenium/standalone-firefox:2.53.1` runtests-selenium does work.

**Comment by rezonanc-oxid** [comment]
You could use our VM as reference.

https://github.com/OXID-eSales/oxvm_eshop/blob/master/ansible/vars/oxideshop.yml#L52-L60

Hope this helps.

**Comment by ghost** [comment]
Thanks. That Selenium Version is even older, but I think I found the answer. The problem seems to be the composer package oxid-esales/mink-selenium-driver which requires oxid-esales/php-selenium which is deprecated because it does not support the WebDriver which is required for Selenium 3.
Maybe we can add a hint in the Readme that Selenium 3 is not yet supported until WebDriver is used by the required libraries.

**Comment by sauliusstasiukaitis** [comment]
Hi @bla-kw,

I just updated information about selenium version. I think it's good enough to say that the issue is solved. Feel free to update documentation with a pull request if you think how to make it more transparent.

https://github.com/OXID-eSales/testing_library#writing-acceptance-tests
