### ISSUE TITLE
[PHP 7.2] Resolve PHPUnit Countable Deprecation Warning

### ISSUE THREAD

**Issue by ps-dfritzsch** [OXID-eSales/testing_library#17]
A lot of PHPUnit **deprecation warnings** from your OXID testing library are spamming our Travis logs, which makes it really hard to identify any relevant errors/warnings related to our production code.

Therefore, we kindly ask you to upgrade the PHPUnit version in order to resolve these warnings **for PHP 7.2**. Please, let us know about the priority & timeline for this improvement request.

```
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/vendor/oxid-esales/testing-library/library/Deprecated.php on line 179
PHP Stack trace:
1. {main}() /var/www/html/vendor/phpunit/phpunit/phpunit:0
2. PHPUnit_TextUI_Command::main() /var/www/html/vendor/phpunit/phpunit/phpunit:47
3. PHPUnit_TextUI_Command->run() /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php:100
4. PHPUnit_TextUI_TestRunner->doRun() /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php:149
5. PHPUnit_Framework_TestSuite->run() /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:440
6. PHPUnit_Framework_TestSuite->run() /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php:747
7. FormInteractionControllerTest->run() /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php:747
8. FormInteractionControllerTest->run() /var/www/html/vendor/oxid-esales/testing-library/library/UnitTestCase.php:149
9. PHPUnit_Framework_TestResult->run() /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php:724
10. FormInteractionControllerTest->runBare() /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php:612
11. FormInteractionControllerTest->runTest() /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php:768
12. ReflectionMethod->invokeArgs() /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php:908
13. FormInteractionControllerTest->testInitWithoutResponse() /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php:908
14. oxTestModules::addFunction() /var/www/html/source/modules/wirecard/paymentgateway/Tests/Unit/Controller/FormInteractionControllerTest.php:47
```

See also:
```
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/vendor/oxid-esales/oxideshop-ce/source/Application/Model/Basket.php on line 1621
...
```

**Comment by Sieg** [comment]
Hello @ps-dfritzsch! What versions are you referring to? As i remember, we have fixed a lot of those in b-6.x and up.

Just double-checked, one of those commits: https://github.com/OXID-eSales/testing_library/commit/29677499ee09cd2b772f4549cd89ec100f9cabf8

**Comment by ps-dfritzsch** [comment]
@Sieg Thank you for the quick response.

We are targeting OXID v6.1.2 (**dev-b-6.1-ce** from https://packagist.org/packages/oxid-esales/oxideshop-project) that already comes with the **testing library v5.0.7** pre-installed.

Please let us know when an official **'oxideshop-project' upgrade** (dev-build) will be available for OXID 6 CE.

**Comment by kermie** [comment]
No probs. Just follow the RSS feed https://oxidforge.org/de/shop/aktuelles/feed (or via Telegram https://t.me/oxid_eshop_important_news) for information about new releases. However, 6.2.0-beta1 (for devs) is already tagged and contains the required functionality.
