### ISSUE TITLE
runmetrics gives 2520 lines of notices

### ISSUE THREAD

**Issue by rezonanc-oxid** [OXID-eSales/testing_library#2]
This is a forward of issue from: https://github.com/OXID-eSales/oxvm_eshop/issues/3 as it is only related with testing library.

**Comment by Shiftas** [comment]
Fixed on both master and b-1.0 branches

https://github.com/OXID-eSales/testing_library/commit/a4336affe9c4a46ae8cec6bb1248f064d70cb125
https://github.com/OXID-eSales/testing_library/commit/d81b85002d9ce75f8ebbcfef3f5318bcbce473ab
