### ISSUE TITLE
executeCommand should return exit code as int

### ISSUE THREAD

**Issue by fjbender** [OXID-eSales/testing_library#28]
In https://github.com/OXID-eSales/testing_library/blob/195554d2545a1940704071cf3ef5dc875485891f/library/Services/Library/DatabaseHandler.php#L241-L256
the Exception and the stack trace is returned, which is okay for running tests manually.

However, in a CI pipeline, if the database setup fails (e.g. through a faulty container setup), the run is interpreted as okay, because the string exit code is interpreted as `0` by e.g. Github Actions. See for instance https://github.com/PAYONE-GmbH/oxid-6/runs/2078035770?check_suite_focus=true#step:11:1

This can be a serious problem, as it might go unnoticed in CI builds that then show up as green wrongfully.

**Comment by Sieg** [comment]
Hey @fjbender, thanks for reporting this. As the component is deprecated and is not used for a while in the new stuff, closing the issue as well.
