### ISSUE TITLE
is_dir is case insensitive on mac

### ISSUE THREAD

**Issue by C3000** [OXID-eSales/testing_library#30]
In the method getTestSuitePath there is a check if the path to the directory is /tests/ or /Tests/.
This check fails on Mac OSX for directories like /Foo/Tests/ because the OS is often case insensitive.
I don't know a suitable method but maybe the check could be switched from /tests/ and /Tests/ to /Tests/ and /tests/.
This would be better while working with composer.

Regards
Markus

**Comment by Sieg** [comment]
Hey @C3000, thanks for reporting this. In general, the solution is - not to use the testing library at all in the future, the component is deprecated.
