### ISSUE TITLE
add note about needed setup directory

### ISSUE THREAD

**Issue by SvenBrunk** [OXID-eSales/testing_library#4]
actually an installed shop is counter-productive for the tests to run. The setup directory is needed and used in running the tests. So either add a note to re-add it (because then you can still use and test the shop manually) or tell people not to install the shop at all

**Comment by Shiftas** [comment]
Added error message when setup directory is not found during shop installation. There is also 'shop_setup_path' parameter, which can be used to specify where setup can be found, if it is not present in shop. Is that sufficient?

**Comment by SvenBrunk** [comment]
That is both great!
But I must excuse myself for the bad ticket description. This was more about documentation than code. An error message during test startup is also good though :)

**Comment by sauliusstasiukaitis** [comment]
It looks like the issue was closed. Feel free to reopen it if I am wrong.

**Comment by SvenBrunk** [comment]
no. all fine. Since the new parameter was nicely documented, this issue was kind of "overfulfilled" ;) Thank you very much
