### ISSUE TITLE
class_exists deckt keine interfaces / traits ab.

### ISSUE THREAD

**Issue by umhaas** [OXID-eSales/testing_library#5]
Interfaces werden nicht abgefangen, somit kommt es zu ein redeclare. 

_Master:_
ModuleLoader.php Zeile 165

_Branch b-1.0_
oxTestModuleLoader.php Zeile 141

_Lösung:_
Abfrage erweitern mit interface-exists().

http://php.net/manual/de/function.interface-exists.php

=> trait_exists() ebenfalls beachten (_achtung_ erst ab 5.4 möglich! Hier also zunächst php version oder function exists prüfen, da ja noch 5.3.25 unterstützt wird von oxid..)

**Comment by Shiftas** [comment]
Hi, I have added a fix with https://github.com/OXID-eSales/testing_library/commit/49896c08b76f17326011212b4a73c5ee21890a65 and https://github.com/OXID-eSales/testing_library/commit/48c6311249b0321408f36e47e0a9c87bf286f6e0 commits.
