### ISSUE TITLE
Information about compatibility

### ISSUE THREAD

**Issue by hendrikfreytag** [OXID-eSales/testing_library#7]
Looks at this link: https://github.com/OXID-eSales/testing_library/tree/b-1.0

+------------------+-----------+---------+
| eShop version    | UTF 0     | UTF 1   |
+==================+===========+=========+
| development      |    ✘      |    ✘    |
+------------------+-----------+---------+
| v4.9.4 and above |    ✔ [*]_ |    ✔    |
+------------------+-----------+---------+
| v5.2.4 and above |    ✔      |    ✔    |
+------------------+-----------+---------+
| v4.7.0 - v4.9.3  |    ✔/✘    |   ✔/✘   |
+------------------+-----------+---------+
| v5.0.0 - v5.2.3  |    ✔/✘    |   ✔/✘   |
+------------------+-----------+---------+
| v4.6.x           |    ✘      |    ✘    |
+------------------+-----------+---------+

It says I could test modules with 5.0.x. This information could be wrong.

I wanted to test a module with 5.0.11. I tried that but it looks like the testing library tries to activate the module in the old way. I got this error:

Adding unit tests from /var/www/html/modules/hf/example/tests//unit/*[^8]Test.php
PHP Fatal error:  Class 'oxModuleCache' not found in /var/www/html/vendor/oxid-esales/testing-library/library/oxTestModuleLoader.php on line 103

I think the class 'oxModuleCache' was introduced in 5.2.0. So maybe it is not compatible with 5.0.x and 5.1.x even if I just want to test modules?

**Comment by sauliusstasiukaitis** [comment]
Hi @hendrikfreytag did you try with some older Testing Library version? For example with 1.0.1 ?

**Comment by hendrikfreytag** [comment]
Tried it with 1.0.0-alpha7. It worked without problems.

**Comment by sauliusstasiukaitis** [comment]
I tried a module with last known good version 1.0.1. Looks like it should work.

The information about compatibility was updated:
https://github.com/OXID-eSales/testing_library/commit/e11ce70db337c11f5a6715a15c09a33352a2f190
