### ISSUE TITLE
runmetrics binary argument error

### ISSUE THREAD

**Issue by mvedegys** [OXID-eSales/testing_library#9]
I needed more paths to be ignored when running metrics, so I expected that 
`vendor/bin/runmetrics "--ignore=myCustomPath"` 
command would do that, but error occurs: 
`Unknown option '<path_to_suite>' given.`

This could be solved by switching places of `$suite/../` and `$arguments`  [here](https://github.com/OXID-eSales/testing_library/blob/master/bin/runmetrics#L49) : 

`$arguments $suite/../` instead of `$suite/../ $arguments`

**Comment by MantasVaitkunas** [comment]
PR #10 did not solve the issue completely, as the script was using predefined --ignore option values. So I added a possibility to overwrite --ignore values. For example:
```bash
vendor/bin/runmetrics --ignore=vendor,tests,out,source/modules
```
